'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, BarChart3, BrainCircuit, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Database, FileText, Gauge, History, Info, Link2, LockKeyhole, Play, RefreshCw, ShieldAlert, ShieldCheck, Sparkles, Terminal, UserRound, Webhook, X, Zap } from 'lucide-react';

const scenarios = {
  'Duplicate payment': { id:'pay_8F2A91', amount:8999, state:'DUPLICATE_RISK', confidence:94.7, action:'DO NOT RETRY', method:'UPI', bank:'HDFC', reason:'Authorization evidence exists and the customer retried after a client timeout.', risk:'HIGH', evidence:['Authorization signal received','Customer retry detected','Original attempt not fully settled'], policy:'Block retry when authorization exists or settlement state is ambiguous.', savings:8999 },
  'Late authorization': { id:'pay_41BC20', amount:4999, state:'LATE_AUTHORIZATION', confidence:92.1, action:'VERIFY', method:'Card', bank:'ICICI', reason:'Authorization arrived after the merchant client marked the attempt as failed.', risk:'MEDIUM', evidence:['Client timeout recorded','Late authorization received','Settlement status requires verification'], policy:'Verify gateway state before any recovery action.', savings:4999 },
  'Confirmed failure': { id:'pay_72D118', amount:1299, state:'CONFIRMED_FAILURE', confidence:98.2, action:'RECOVER', method:'UPI', bank:'SBI', reason:'No authorization signal; failure appears genuine and one bounded recovery attempt is allowed.', risk:'LOW', evidence:['Gateway failure confirmed','No authorization evidence','Recovery policy matched'], policy:'Allow one bounded recovery attempt after confirmed failure.', savings:0 },
  'Unknown state': { id:'pay_3CA771', amount:15999, state:'UNKNOWN', confidence:71.4, action:'ESCALATE', method:'Card', bank:'Axis', reason:'Conflicting signals remain unresolved; human review prevents unsafe automation.', risk:'HIGH', evidence:['Conflicting gateway signals','Missing final settlement event','Insufficient evidence for safe automation'], policy:'Escalate unresolved payment states to human review.', savings:0 }
};

const basePayments = Object.values(scenarios).map((p, i) => ({...p, events:[5,4,3,2][i]}));
const DEFAULT_BATCH_METRICS = {
  seed: 42, processed: 10000, atRisk: 21491290, recoveryCandidates: 1249, recoveredCount: 1049,
  recoveredAmount: 5427020, recoveryRate: 0.8398718975180144, unsafeBlockedRate: 1, unsafeBlocked: 2208, unsafeAttempts: 0,
  decisionAccuracy: 0.8751, escalationRate: 0.8399, avgDecisionMs: 28,
  baseline: { recoveredCount: 1049, recoveredAmount: 5427020, unsafeAttempts: 325 },
  improvement: { unsafeActionsAvoided: 325, revenueProtected: 0 },
  sample: []
};

const scenarioEvents = {
  'Duplicate payment': [['17:42:01','Payment initiated','ok'],['17:42:08','Client timeout','warn'],['17:42:13','Authorization signal received','ok'],['17:42:20','Customer retry detected','warn'],['17:42:21','Policy gate evaluated','ok']],
  'Late authorization': [['17:51:01','Payment initiated','ok'],['17:51:09','Client timeout','warn'],['17:51:18','Authorization received late','warn'],['17:51:19','Settlement verification required','ok'],['17:51:20','Policy gate evaluated','ok']],
  'Confirmed failure': [['18:02:01','Payment initiated','ok'],['18:02:07','Gateway failure confirmed','warn'],['18:02:08','No authorization evidence','ok'],['18:02:09','Retry-safe window checked','ok'],['18:02:10','Policy gate evaluated','ok']],
  'Unknown state': [['18:10:01','Payment initiated','ok'],['18:10:08','Gateway timeout','warn'],['18:10:12','Conflicting status signal','warn'],['18:10:13','Final settlement missing','warn'],['18:10:14','Human review required','ok']]
};
const timeline = scenarioEvents['Duplicate payment'];
const batchRows = [
  ['pay_01A2','₹8,999','Duplicate risk','DO NOT RETRY','blocked'],['pay_02B4','₹4,999','Late auth','VERIFY','verified'],['pay_03C7','₹1,299','Confirmed failure','RECOVER','recovered'],['pay_04D1','₹15,999','Unknown','ESCALATE','human'],['pay_05E8','₹2,499','Confirmed failure','RECOVER','recovered']
];
function money(n){return '₹'+Math.round(n).toLocaleString('en-IN')}
function State({s}){return <span className={'state '+s.toLowerCase().replaceAll(' ','_')}>{s.replaceAll('_',' ')}</span>}
function Metric({icon,label,value,note}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><b>{value}</b><small>{note}</small></div></div>}

export default function Home(){
 const [payments,setPayments]=useState(basePayments); const [selected,setSelected]=useState(basePayments[0]); const [filter,setFilter]=useState('ALL'); const [scenario,setScenario]=useState('Duplicate payment');
 const [running,setRunning]=useState(false); const [backend,setBackend]=useState(null); const [diagnosis,setDiagnosis]=useState(null); const [batchRunning,setBatchRunning]=useState(false); const [showWhy,setShowWhy]=useState(false); const [showAudit,setShowAudit]=useState(false); const [showConnect,setShowConnect]=useState(false); const [toast,setToast]=useState('');
 const [recovered,setRecovered]=useState(DEFAULT_BATCH_METRICS.recoveredAmount); const [blocked,setBlocked]=useState(DEFAULT_BATCH_METRICS.unsafeBlocked); const [batchRecovered,setBatchRecovered]=useState(DEFAULT_BATCH_METRICS.recoveredCount); const [batchProcessed,setBatchProcessed]=useState(DEFAULT_BATCH_METRICS.processed); const [batchMetrics,setBatchMetrics]=useState(DEFAULT_BATCH_METRICS); const [counterfactual,setCounterfactual]=useState(null);
 const visible=useMemo(()=>filter==='ALL'?payments:payments.filter(p=>p.state===filter),[payments,filter]);
 const notify=(msg)=>{setToast(msg);setTimeout(()=>setToast(''),3000)};
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setBackend).catch(()=>setBackend({ok:false}));},[]);
 const runAnalysis=async(target=selected)=>{setRunning(true);try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment:target,events:(scenarioEvents[Object.keys(scenarios).find(k=>scenarios[k].id===target.id)]||timeline).map(([time,event])=>({time,event}))})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Analysis failed');const next={...target,state:data.policy.action==='VERIFY'?'LATE_AUTHORIZATION':data.diagnosis.state,action:data.policy.action,confidence:Number(data.diagnosis.confidence)*100,reason:data.diagnosis.reason||target.reason,provider:data.diagnosis.provider,audit_id:data.audit_id,evidence:target.evidence,policy:data.policy.reason,risk:Number(data.diagnosis.duplicate_charge_risk)>0.8?'HIGH':Number(data.diagnosis.confidence)<0.85?'MEDIUM':'LOW'};setDiagnosis(data);setPayments(ps=>ps.map(x=>x.id===next.id?next:x));setSelected(next);notify(`${data.diagnosis.provider==='openai'?'AI':'Safety fallback'} diagnosis complete · ${data.policy.action}`);}catch(e){notify(`Backend analysis failed: ${e.message}`)}finally{setRunning(false)}};
 const runScenario=()=>{const p={...scenarios[scenario]};setPayments(ps=>ps.map(x=>x.id===p.id?{...x,...p}:x));runAnalysis(p)};
 const runCounterfactual=async()=>{try{const res=await fetch('/api/counterfactual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment:selected,simulation:true,diagnosis:diagnosis?.diagnosis||{state:selected.state,confidence:selected.confidence/100,duplicate_charge_risk:selected.risk==='HIGH'?0.9:0.05}})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Counterfactual failed');setCounterfactual(data);notify('Counterfactual decision analysis complete')}catch(e){notify(e.message)}};
 const recover=async()=>{if(['DO NOT RETRY','RECOVERED'].includes(selected.action)) return;try{const res=await fetch('/api/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment:selected,simulation:true,diagnosis:diagnosis?.diagnosis||{state:selected.state,confidence:selected.confidence/100,duplicate_charge_risk:selected.risk==='HIGH'?0.9:0.05,recommended_action:'RECOVER'}})});const data=await res.json();if(!res.ok)throw new Error(data.error||data.policy?.reason||'Recovery blocked');const next={...selected,action:'RECOVERY ORDER CREATED',state:'RECOVERY_PENDING',confidence:99.1};setPayments(ps=>ps.map(p=>p.id===selected.id?next:p));setSelected(next);setRecovered(v=>v+selected.amount);setBatchRecovered(v=>v+1);notify(`Recovery adapter executed · ${data.result?.id||'order created'}`);}catch(e){notify(`Recovery stopped: ${e.message}`)}};
 const runBatch=async()=>{if(batchRunning)return;setBatchRunning(true);try{const res=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({size:10000,seed:42})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Benchmark failed');const m=data.metrics;setBatchMetrics(m);setBatchProcessed(m.processed);setBatchRecovered(m.recoveredCount);setBlocked(m.unsafeBlocked ?? Math.round(m.unsafeBlockedRate*m.processed));setRecovered(m.recoveredAmount);notify(`Benchmark complete · ${m.processed.toLocaleString('en-IN')} events evaluated`)}catch(e){notify(`Benchmark failed: ${e.message}`)}finally{setBatchRunning(false)}};
 const atRisk=payments.filter(p=>p.state!=='CONFIRMED_SUCCESS').reduce((a,p)=>a+p.amount,0);
 const recoveryRate=batchMetrics?(batchMetrics.recoveryRate*100).toFixed(1):'—';
 return <main>
  <header className="topbar"><div className="brand"><div className="logo"><ShieldCheck size={17}/></div><span>RAID</span><small>AI REVENUE RECOVERY CONTROL PLANE</small></div><div className="top-actions"><span className="live"><i/> RAZORPAY TEST MODE</span><span className="backend-status">{backend?.ok ? (backend.database ? "API + DB ONLINE" : "API ONLINE · DB OFF") : "CONNECTING…"}</span><button onClick={()=>runAnalysis()} className="primary"><Sparkles size={14}/>{running?'Analyzing…':'Run AI Analysis'}</button></div></header>

  <section className="hero"><div className="hero-copy"><p className="eyebrow">AGENTIC REVENUE RECOVERY · v3.0</p><h1>Recover revenue.<br/><em>Never recover recklessly.</em></h1><p className="sub">RAID detects revenue at risk, reconstructs ambiguous payment states, chooses a bounded intervention, verifies the outcome and records the evidence — closing the recovery loop.</p><div className="hero-buttons"><button className="primary big" onClick={()=>document.getElementById('batch').scrollIntoView({behavior:'smooth'})}><Play size={15}/> Run recovery batch</button><button className="ghost" onClick={()=>setShowConnect(true)}><Link2 size={15}/> Connect test events</button></div><div className="hero-proof"><span><CheckCircle2/> AI diagnosis</span><span><CheckCircle2/> Policy gated</span><span><CheckCircle2/> Measured recovery</span></div></div><div className="hero-orbit"><div className="orbit-core"><BrainCircuit/><span>RAID<br/><small>RECOVERY AGENT</small></span></div><div className="orbit-label l1">DETECT</div><div className="orbit-label l2">DIAGNOSE</div><div className="orbit-label l3">DECIDE</div><div className="orbit-label l4">EXECUTE</div><div className="orbit-label l5">VERIFY</div></div></section>

  <section className="metrics"><Metric icon={<AlertTriangle/>} label="Revenue at risk" value={money(atRisk)} note="live exception queue"/><Metric icon={<CircleDollarSign/>} label="Revenue recovered" value={money(recovered)} note="synthetic benchmark"/><Metric icon={<ShieldAlert/>} label="Unsafe actions blocked" value={blocked} note="policy-gated decisions"/><Metric icon={<BarChart3/>} label="Batch recovery rate" value={batchMetrics?recoveryRate+'%':'—'} note={batchMetrics?batchRecovered+' / '+batchMetrics.recoveryCandidates+' candidates recovered':'run benchmark to measure'}/></section>

  <section className="batch" id="batch"><div className="section-title"><div><p className="eyebrow">01 · MEASURED AGENT RUN</p><h2>Revenue Recovery Command Center</h2><p>Don't show one cherry-picked payment. Run RAID across a synthetic batch and measure the money it recovers.</p></div><div className="batch-actions"><span className="test-badge"><Database size={14}/> SYNTHETIC EVAL</span><button className="primary" onClick={runBatch}><Zap size={14}/>{batchRunning?'Running agent…':'Run 10,000 transactions'}</button></div></div><div className="batch-grid"><div className="batch-hero-card"><div className="batch-number"><span>SIMULATED RECOVERY VALUE</span><strong>{money(batchMetrics?.recoveredAmount||0)}</strong><small>from {batchProcessed.toLocaleString('en-IN')} synthetic events · no money moved</small></div><div className="batch-bars"><div><span>At risk</span><b>{batchMetrics?money(batchMetrics.atRisk):'—'}</b><i><em style={{width:'82%'}}/></i></div><div><span>Recovery candidates</span><b>{batchMetrics?.recoveryCandidates??'—'}</b><i><em style={{width:'52%'}}/></i></div><div><span>Recovered</span><b>{batchRecovered}</b><i><em style={{width:recoveryRate+'%'}}/></i></div></div></div><div className="score-grid"><Score title="Recovery rate" value={recoveryRate+'%'} sub="candidate → recovered"/><Score title="Unsafe action block" value={batchMetrics?(batchMetrics.unsafeBlockedRate*100).toFixed(1)+'%':'—'} sub="policy violations stopped"/><Score title="Escalation" value={batchMetrics?(batchMetrics.escalationRate*100).toFixed(1)+'%':'—'} sub="human review"/><Score title="Avg. decision" value={batchMetrics?batchMetrics.avgDecisionMs+'ms':'—'} sub="benchmark decision time"/></div></div></section>

  <section className="simulator" id="simulator"><div className="section-title"><div><p className="eyebrow">02 · ROOT CAUSE → ACTION</p><h2>Decision Simulator</h2><p>Pick a failure mode. RAID reconstructs the event sequence, compares outcomes, and selects a bounded action.</p></div><div className="test-badge"><Webhook size={14}/> EVENT STREAM</div></div><div className="sim-grid"><div className="scenario-card"><div className="card-label">SELECT FAILURE MODE</div>{Object.keys(scenarios).map(s=><button key={s} className={'scenario '+(scenario===s?'active':'')} onClick={()=>setScenario(s)}><span><span className="scenario-dot"/>{s}</span><ChevronRight size={15}/></button>)}<button className="run-sim" onClick={runScenario}><Sparkles size={15}/>{running?'Reconstructing…':'Run reconstruction'}</button></div><div className="decision-card"><div className="decision-top"><div><div className="card-label">AI DIAGNOSIS</div><h3>{scenarios[scenario].id}</h3></div><span className={'risk '+scenarios[scenario].risk.toLowerCase()}>{scenarios[scenario].risk} RISK</span></div><div className="decision-flow"><Flow icon={<Database/>} label="Events" value={scenarios[scenario].events}/><ArrowRight/><Flow icon={<BrainCircuit/>} label="Diagnosis" value="AI"/><ArrowRight/><Flow icon={<LockKeyhole/>} label="Guardrails" value="GATED"/><ArrowRight/><Flow final icon={<Gauge/>} label="Action" value={scenarios[scenario].action}/></div><div className="decision-result"><span>RECOMMENDED ACTION</span><strong>{scenarios[scenario].action}</strong><div className="confidence-mini"><span>Confidence {scenarios[scenario].confidence}%</span><div><i style={{width:scenarios[scenario].confidence+'%'}}/></div></div></div><button className="explain-cta" onClick={()=>setShowWhy(true)}><Info size={14}/> Show evidence & policy <ArrowRight size={13}/></button><button className="explain-cta" onClick={runCounterfactual}><BarChart3 size={14}/> Compare recovery outcomes <ArrowRight size={13}/></button></div></div></section>

  <section className="workspace"><div className="panel table-panel"><div className="panel-head"><div><p className="eyebrow">03 · OPERATIONS</p><h2>Payment Exceptions</h2><p>Every recommendation is explainable and policy gated.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option><option>DUPLICATE_RISK</option><option>LATE_AUTHORIZATION</option><option>CONFIRMED_FAILURE</option><option>UNKNOWN</option><option>CONFIRMED_SUCCESS</option></select></div><div className="table"><div className="tr th"><span>PAYMENT</span><span>AMOUNT</span><span>STATE</span><span>CONFIDENCE</span><span>ACTION</span></div>{visible.map(p=><button className={'tr row '+(selected.id===p.id?'selected':'')} key={p.id} onClick={()=>setSelected(p)}><span><strong>{p.id}</strong><small>{p.method} · {p.bank} · {p.events} events</small></span><span>{money(p.amount)}</span><span><State s={p.state}/></span><span>{p.confidence}%</span><span className="action">{p.action}</span></button>)}</div></div>
  <div className="panel detail"><div className="detail-head"><div><span className="tiny">SELECTED PAYMENT</span><h2>{selected.id}</h2></div><State s={selected.state}/></div><div className="amount">{money(selected.amount)} <small>{selected.method} · {selected.bank}</small></div><div className="confidence"><div><span>AI confidence</span><b>{selected.confidence}%</b></div><div className="bar"><i style={{width:selected.confidence+'%'}}/></div></div><div className="reason"><div className="reason-title"><BrainCircuit size={15}/> ROOT CAUSE</div><strong>{selected.action}</strong><p>{selected.reason}</p><button className="why" onClick={()=>setShowWhy(true)}>Explain why <ArrowRight size={13}/></button></div><div className="timeline">{(scenarioEvents[Object.keys(scenarios).find(k=>scenarios[k].id===selected.id)]||timeline).map(([t,title,type])=><div className="event" key={t}><Clock3 size={14}/><time>{t}</time><span className={type}>{title}</span><i className={type==='ok'?'ok':''}/></div>)}</div><div className="audit"><span>AUTONOMOUS AUTHORITY</span><b>₹0</b><span>AUDIT ID</span><code>{selected.audit_id || `raid_${selected.id.slice(-6).toLowerCase()}`}</code></div>{selected.action!=='DO NOT RETRY'&&selected.action!=='RECOVERED'&&<button className="recover" onClick={recover}><Check size={14}/> Execute bounded recovery</button>}<button className="audit-link" onClick={()=>setShowAudit(true)}><History size={14}/> View full audit trail</button></div></section>

  <section className="why-ai" id="why-ai"><div className="section-title"><div><p className="eyebrow">04 · WHY AI, WHY NOW</p><h2>AI handles ambiguity. Policy controls money.</h2><p>Payment failures are event sequences, not single labels. RAID uses AI for contextual diagnosis, then hands the final authority to deterministic rules.</p></div></div><div className="compare-grid"><div className="compare-card muted-card"><span>TRADITIONAL RULES</span><h3>Fast, but brittle</h3><ul><li>Looks at isolated status codes</li><li>Fixed failure categories</li><li>Hard-coded recovery branches</li><li>Weak handling of conflicting evidence</li></ul></div><div className="compare-arrow"><ArrowRight/></div><div className="compare-card"><span>RAID</span><h3>Context + control</h3><ul><li>Reconstructs multi-event payment state</li><li>Explains root cause with confidence</li><li>Separates AI recommendation from execution</li><li>Escalates when evidence is insufficient</li></ul></div></div><div className="pipeline-strip"><b>OBSERVE</b><ArrowRight/><b>RECONSTRUCT</b><ArrowRight/><b>DIAGNOSE</b><ArrowRight/><b>PREDICT</b><ArrowRight/><b>POLICY GATE</b><ArrowRight/><b>VERIFY</b></div></section>

  <section className="guardrails"><div className="section-title"><div><p className="eyebrow">05 · SAFETY CONTROLS</p><h2>Every AI recommendation meets a hard policy gate.</h2><p>The model can suggest. It cannot bypass amount limits, duplicate-risk thresholds, confidence requirements or verification checkpoints.</p></div></div><div className="guard-grid"><Guard title="Duplicate risk" ai="RETRY" policy="BLOCK" reason="Authorization evidence exists"/><Guard title="Ambiguous state" ai="RECOVER" policy="ESCALATE" reason="Confidence below threshold"/><Guard title="Confirmed failure" ai="RECOVER" policy="ALLOW" reason="Bounded amount + low duplicate risk"/><Guard title="Late authorization" ai="RECOVER" policy="VERIFY" reason="Settlement must be checked first"/></div></section>

  <section className="evaluation"><div className="section-title"><div><p className="eyebrow">06 · EVALUATION METHODOLOGY</p><h2>Numbers with a reproducible story.</h2><p>This server-side benchmark generates a reproducible synthetic payment universe, scores every event sequence, applies RAID policy, and compares it with a naive recovery baseline. It never calls Razorpay or moves money.</p></div><span className="test-badge"><Database size={14}/> 10,000 EVENTS</span></div><div className="eval-grid"><div className="eval-card"><span>RAID RECOVERY</span><strong>{batchMetrics?recoveryRate+'%':'—'}</strong><small>candidate → recovered</small></div><div className="eval-card"><span>DECISION ACCURACY</span><strong>{batchMetrics?(batchMetrics.decisionAccuracy*100).toFixed(1)+'%':'—'}</strong><small>expected action matched</small></div><div className="eval-card"><span>UNSAFE BLOCK</span><strong>{batchMetrics?(batchMetrics.unsafeBlockedRate*100).toFixed(1)+'%':'—'}</strong><small>unsafe recovery attempts stopped</small></div><div className="eval-card"><span>VS BASELINE</span><strong>{batchMetrics?batchMetrics.improvement.unsafeActionsAvoided:'—'}</strong><small>unsafe actions avoided</small></div></div><div className="method-row"><div><b>Dataset</b><span>Synthetic payment-event sequences with known outcomes.</span></div><div><b>Measure</b><span>Recovery conversion, unsafe-action blocks and escalation.</span></div><div><b>Guardrail</b><span>AI never directly authorizes money movement.</span></div></div></section>

  <section className="scenarios"><div className="section-title"><div><p className="eyebrow">07 · FAILURE LAB</p><h2>Four incidents. Four different decisions.</h2><p>Use these scenarios during the jury demo to prove RAID is not a one-path chatbot.</p></div></div><div className="failure-grid">{Object.entries(scenarios).map(([name,p])=><button key={name} className="failure-card" onClick={()=>{setScenario(name);document.getElementById('simulator').scrollIntoView({behavior:'smooth'});}}><div><span>{name}</span><b>{p.action}</b></div><p>{p.reason}</p><small>{p.events} events · {p.confidence}% confidence · {p.risk} risk</small><ArrowRight/></button>)}</div></section>

  <section className="architecture"><div className="section-title"><div><p className="eyebrow">08 · SYSTEM ARCHITECTURE</p><h2>AI can recommend. Policy controls money.</h2><p>RAID separates reasoning from execution so a model never gets unlimited financial authority.</p></div></div><div className="arch-flow">{[['DETECT',Database,'Find revenue at risk from payment events'],['DIAGNOSE',BrainCircuit,'Reconstruct state + identify root cause'],['DECIDE',Gauge,'Choose the highest-value safe intervention'],['GUARDRAIL',LockKeyhole,'Enforce amount, retry and stopping limits'],['VERIFY',CheckCircle2,'Confirm outcome + write immutable audit evidence']].map(([t,I,d],i)=><div className="arch-step" key={t}><div className="arch-icon"><I/></div><span>0{i+1}</span><h3>{t}</h3><p>{d}</p>{i<4&&<ArrowRight className="arch-arrow"/>}</div>)}</div></section>

  <section className="integration"><div><p className="eyebrow">09 · RAZORPAY INTEGRATION</p><h2>Built to sit on top of payment infrastructure.</h2><p>RAID is engineered to ingest Razorpay payment webhooks — <b>payment.failed</b>, <b>payment.authorized</b> and <b>payment.captured</b> — with HMAC signature verification and idempotent event handling. The demo remains synthetic until a server-side webhook secret is configured.</p><button className="ghost" onClick={()=>setShowConnect(true)}><Webhook size={14}/> Open event adapter</button></div><div className="adapter"><div className="adapter-head"><span><i className="green-dot"/> EVENT ADAPTER</span><span>{backend?.webhook ? 'WEBHOOK READY' : 'IMPLEMENTED · SECRET REQUIRED'}</span></div><div className="code-line"><span>POST</span><b>/api/razorpay/webhook</b></div><div className="code-line"><span>EVENT</span><b>payment.failed</b></div><div className="code-line"><span>EVENT</span><b>payment.authorized</b></div><div className="code-line"><span>EVENT</span><b>payment.captured</b></div><div className="adapter-foot"><CheckCircle2 size={14}/> HMAC validation · idempotent event processing · no direct model authority</div></div></section>

  <section className="audit-section"><div><p className="eyebrow">10 · TECHNICAL DEPTH</p><h2>Evidence over vibes.</h2><p>Every recovery claim is tied to a batch metric. Every decision is tied to evidence. Every money-moving action is bounded.</p><div className="principles"><span><ShieldCheck/> Defense-first</span><span><BarChart3/> Measured</span><span><FileText/> Auditable</span></div></div><div className="tech-grid"><Tech icon={<BrainCircuit/>} title="AI Reasoning" text="Structured transaction-event reconstruction, root-cause diagnosis and confidence scoring."/><Tech icon={<LockKeyhole/>} title="Policy Engine" text="Deterministic action limits, retry caps, amount bounds and stopping conditions."/><Tech icon={<Terminal/>} title="Execution Adapter" text="Only policy-approved recovery actions can reach an execution connector."/><Tech icon={<FileText/>} title="Audit Trail" text="Evidence, decision, policy, timestamps and outcome are linked to one audit ID."/></div></section>

  <footer><span><ShieldCheck size={15}/> RAID · Recover revenue without recovering recklessly.</span><span>Prototype · Synthetic Evaluation · Test Mode</span></footer>

  {showWhy&&<Modal title="Why did RAID choose this?" onClose={()=>setShowWhy(false)}><div className="modal-decision"><span>DECISION</span><strong>{selected.action}</strong><b>{selected.confidence}% confidence · {selected.risk} risk</b></div><div className="evidence">{selected.evidence.map((x,i)=><div key={x}><CheckCircle2 size={15}/><span><b>Evidence {i+1}</b>{x}</span></div>)}</div><div className="policy"><LockKeyhole size={15}/><div><span>POLICY GATE</span><p>{selected.policy}</p></div></div></Modal>}
  {counterfactual&&<Modal title="Counterfactual recovery" onClose={()=>setCounterfactual(null)}><div className="counterfactual"><div className="cf-recommended"><span>BEST EXPECTED VALUE</span><strong>{counterfactual.recommended.action}</strong><b>{money(counterfactual.recommended.expected_value)} expected value</b></div>{counterfactual.options.map(o=><div className="cf-row" key={o.action}><div><b>{o.action}</b><span>{o.explanation}</span></div><strong>{money(o.expected_value)}</strong></div>)}<small className="cf-note">{counterfactual.assumptions}</small></div></Modal>}
  {showAudit&&<Modal title="Audit trail" onClose={()=>setShowAudit(false)}><div className="audit-list">{['Event ingestion','Idempotency check','State reconstruction','Root-cause evaluation','Policy gate','Action recorded','Verification checkpoint'].map((x,i)=><div key={x}><span>17:42:{String(1+i*3).padStart(2,'0')}</span><b>{x}</b><em>PASS</em></div>)}</div><div className="audit-id"><span>AUDIT ID</span><code>{selected.audit_id || `raid_${selected.id.slice(-6).toLowerCase()}`}</code></div></Modal>}
  {showConnect&&<Modal title="Razorpay test-event adapter" onClose={()=>setShowConnect(false)}><div className="connect-card"><div className="connected"><CheckCircle2 size={18}/><div><b>{backend?.webhook ? 'Webhook validation enabled' : 'Webhook adapter implemented'}</b><span>{backend?.webhook ? 'HMAC signature verification + idempotency active' : 'Add RAZORPAY_WEBHOOK_SECRET to enable live signature validation'}</span></div></div><div className="connect-lines"><div><span>Endpoint</span><code>/api/razorpay/webhook</code></div><div><span>Supported events</span><code>failed · authorized · captured</code></div><div><span>Execution authority</span><code>₹0 until policy approval</code></div></div><button className="primary wide" onClick={()=>{setShowConnect(false);notify('Test event adapter armed')}}><Webhook size={14}/> Arm test adapter</button></div></Modal>}
  {toast&&<div className="toast"><CheckCircle2 size={15}/>{toast}</div>}
 </main>
}
function Flow({icon,label,value,final}){return <div className={'flow-step '+(final?'final':'')}>{icon}<span>{label}</span><b>{value}</b></div>}
function Score({title,value,sub}){return <div className="score"><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>}
function Tech({icon,title,text}){return <div className="tech"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Guard({title,ai,policy,reason}){return <div className="guard-card"><span>{title}</span><div><b>AI</b><strong>{ai}</strong><ArrowRight/><b>POLICY</b><strong className={policy==='BLOCK'||policy==='ESCALATE'?'danger':''}>{policy}</strong></div><small>{reason}</small></div>}
function Modal({title,onClose,children}){return <div className="overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={17}/></button><div className="modal-head"><p className="eyebrow">EXPLAINABLE CONTROL</p><h2>{title}</h2></div>{children}</div></div>}
